- name: Run the tester
  hosts: ovn_hosts
  become: true
  tasks:
  - name: Start tester container
    when: ovn_tester is defined
    shell: |
      docker run -dt --name=ovn-tester --hostname=ovn-tester --privileged ovn/ovn-tester

  - name: Copy files to the tester container
    when: ovn_tester is defined
    shell: |
      docker cp {{ test_file }} ovn-tester:/test-scenario.yml

  - name: Add tester container interfaces to OVS bridges
    when: ovn_tester is defined
    shell: |
      cd {{ ovn_fake_multinode_target_path }}/ovn-fake-multinode
      ./ovs-docker add-port br-ovn eth1 ovn-tester --ipaddress={{ tester_ip }}
      ./ovs-docker add-port br-ovn-ext eth2 ovn-tester
